///|
#external
pub type Window

///|
#external
pub type Document

///|
#external
pub type Element

///|
#external
pub type Event

///|
#external
pub type TimeoutHandle

///|
#external
pub type IntervalHandle

///|
#external
pub type AnimationFrameHandle

///|
#external
pub type Node

///|
#external
pub type Text

///|
#external
pub type Comment

///|
#external
pub type EventHandle

///|
#external
pub type JsArray

///|
#external
pub type TemplateElement
