name: ci

on:
  push:
    branches:
      - "main"
      - "clean_code"
  pull_request: 
    branches: 
      - "main"

jobs:
  build:
    name: Build ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] 

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Moonbit
        uses: hustcer/setup-moonbit@v1

      - name: Build native cmd binary
        shell: bash
        run: |
          rm -rf .mooncakes
          moon update
          moon install
          moon build cmd/aitne --target=native --release

      - name: Verify executable 
        shell: bash
        run: |
          ./_build/native/release/build/cmd/aitne/aitne.exe help

  test_and_check:
    name: Test ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] 

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Moonbit
        uses: hustcer/setup-moonbit@v1

      - name: post install
        run: |
          moon version --all
          moon update
          moon install

      - name: moon check
        run: |
          moon check 

      - name: moon test
        run: |
          moon test 

      - name: lint
        run: |
          moon fmt && git diff --exit-code
          moon info && git diff --exit-code
