name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        target:
          - runner: ubuntu-latest
            name: linux-x64
            ext: ""
          - runner: macos-latest
            name: macos-arm64
            ext: ""
#   Maybe will support Windows in future          
#          - runner: windows-latest
#            name: windows-x64
#            ext: ".exe"

    runs-on: ${{ matrix.target.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Moonbit
        uses: hustcer/setup-moonbit@v1
        with: 
          version: "0.10.4+2cc641edf"

      - name: Build Native Cmd Binary
        shell: bash
        run: |
          rm -rf .mooncakes
          moon update
          moon install
          moon build cmd/aitne --target=native --release

      - name: Prepare Artifacts
        shell: bash
        run: |
          mkdir dist

          EXE_EXT="${{ matrix.target.ext }}"

          SRC_BIN=$(find _build/native/release/build/cmd -type f \( -name "aitne.exe" \) | head -n 1)

          if [ -z "$SRC_BIN" ]; then
            echo "Error: Cannot find compiled binary!"
            exit 1
          fi

          cp "$SRC_BIN" "dist/aitne-${{ matrix.target.name }}${EXE_EXT}"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
